# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAPC_app', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plagiarism_Value',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('cosine_value', models.CharField(max_length=50)),
            ],
        ),
    ]
