# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-05-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAPC_app', '0007_auto_20220506_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=30)),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Topicc',
        ),
    ]
