# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-05-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAPC_app', '0008_auto_20220506_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmentt',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('assignment_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
